### ISSUE TITLE
Sync Models utility should delete outdated tables

### ISSUE THREAD

**Issue by loganliffick** [outerbase/sdk#34]
**Is your feature request related to a problem? Please describe.**
Deleted a table in Outerbase, added a new table, ran `sync-models` on my project, new table shows up in models but deleted table remains.

**Describe the solution you'd like**
Add a delete function for non-existent tables.

**Describe alternatives you've considered**
Manually deleting the ts file in the models folder (which feels unintuitive)

**Comment by Brayden** [comment]
Good catch on an issue.

One proposal I can come up with is perhaps we delete the directory one time, each time the `generate-models` code is executed so that all of the folder paths start out clean. We would hope/anticipate users would be sure to keep their `/models` folder (or whichever name or path they choose) to stay isolated from the rest of their code otherwise this could cause unintended consequences.

Examples:
```ts
const deletedPathsMap: Record<string, any> = {}

// ...

if (!deletedPathsMap[currentFolderPath]) {
    await fs.rmdir(currentFolderPath, { recursive: true })
    deletedPathsMap[currentFolderPath] = true
}
```

Thoughts?
